// react-example/src/App.tsx
import { useEffect, useState } from "react";
import Feed from "./components/feed";
import "@blinkoo/components";
import { BlinkooFeedConfiguration, BlinkooWebInit } from "@blinkoo/components";
import SingleVideo from "./components/single-video";

function App() {
  const [isInitialized, setIsInitialized] = useState<boolean>(false);
  const [shownItem, setShownItem] = useState<number>(1);

  const initBlinkooComponents = async () => {
    await BlinkooWebInit.init({
      assetsPath: "blinkoo-assets/",
      customApiBasePath: "http://localhost:4000", // only for development, remove parameter in production
    });
    setIsInitialized(true);
  };

  useEffect(() => {
    initBlinkooComponents();
  }, []);

  if (!isInitialized) return <></>;

  const configurations: BlinkooFeedConfiguration = {
    isCreatorEnabled: true,
  };

  return (
    <>
      <div style={{ height: "600px" }}>
        {shownItem == 1 ? (
          <Feed
            title="Explore"
            aspectRatio={0.5625}
            configurations={configurations}
          ></Feed>
        ) : (
          <SingleVideo postId="POST_ID" title="single video" aspectRatio={1} />
        )}
      </div>
      <button onClick={() => setShownItem(1)}>Show feed</button>
      <button onClick={() => setShownItem(2)}>Show single video</button>
    </>
  );
}

export default App;

// vue-example/src/App.vue
<script setup lang="ts">
import { ref, onMounted } from 'vue'
import FeedVideo from './components/FeedVideo.vue'
import SingleVideo from './components/SingleVideo.vue'
import '@blinkoo/components'
import { BlinkooWebInit, BlinkooFeedConfiguration } from '@blinkoo/components'

const isInitialized = ref(false)
const shownItem = ref(1)

const initBlinkooComponents = async () => {
  await BlinkooWebInit.init({
    assetsPath: 'blinkoo-assets/',
    customApiBasePath: 'http://localhost:4000', // only for development, remove parameter in production
  })
  isInitialized.value = true
}

const configurations: BlinkooFeedConfiguration = {
  isCreatorEnabled: true,
}

onMounted(() => {
  initBlinkooComponents()
})
</script>

<template>
  <div v-if="isInitialized">
    <div style="height: 600px">
      <FeedVideo
        v-if="shownItem === 1"
        title="Explore"
        :aspectRatio="0.5625"
        :configurations="configurations"
      />
      <SingleVideo
        v-else
        postId="POST_ID"
        title="single video"
        :aspectRatio="1"
      />
    </div>
  </div>
  <button @click="shownItem = 1">Show feed</button>
  <button @click="shownItem = 2">Show single video</button>
</template>
