// vue-example/src/components/Feed.vue
<script setup lang="ts">
import { BlinkooFeedArgs } from "@blinkoo/components";

const props = withDefaults(defineProps<{
  title?: string,
  filters?: string,
  playlistFilter?: string,
  aspectRatio?: number,
  feedPosition?: number,
}>(), {
  // default values
  title: "",
  filters: undefined,
  playlistFilter: undefined,
  aspectRatio: undefined,
  feedPosition: undefined
});
</script>

<template>
  <blinkoo-feed :title=title :filters=filters :playlistFilter=playlistFilter :aspectRatio=aspectRatio
    :feedPosition=feedPosition />
</template>

// nextjs-example/src/app/components/feed.tsx
"use client";
import { BlinkooFeedArgs } from "@blinkoo/components";

export default function Feed(params: BlinkooFeedArgs) {

  return (
    <blinkoo-feed
      title={params.title}
      filters={params.filters}
      playlistFilter={params.playlistFilter}
      aspectRatio={params.aspectRatio}
    ></blinkoo-feed>
  );
}
