// nextjs-example/src/app/components/single-video.tsx
"use client";

import {
  BlinkooSingleVideoAttributes,
  BlinkooSingleVideoElement,
} from "@blinkoo/components";
import { forwardRef, useImperativeHandle, useRef } from "react";
import BlinkooComponentWrapper from "./blinkoo-component-wrapper";

type SingleVideoArgs = Omit<BlinkooSingleVideoAttributes, keyof HTMLElement>;

export interface SingleVideoRef {
  togglePlay: () => void;
}

const SingleVideo = forwardRef<SingleVideoRef, SingleVideoArgs>(
  (params, ref) => {
    const singleVideoRef = useRef<BlinkooSingleVideoElement>(null);

    useImperativeHandle(ref, () => ({
      togglePlay: () => singleVideoRef.current?.togglePlay(),
    }));

    return (
      <BlinkooComponentWrapper>
        <blinkoo-single-video
          ref={singleVideoRef}
          environment={params.environment}
          custom-base-url={params["custom-base-url"]}
          external-customer-id={params["external-customer-id"]}
          utm-source={params["utm-source"]}
          utm-campaign={params["utm-campaign"]}
          referrer={params.referrer}
          component-id={params["component-id"]}
          post-id={params["post-id"]}
          autoplay={params.autoplay}
          muted={params.muted}
          show-creator={params["show-creator"]}
        ></blinkoo-single-video>
      </BlinkooComponentWrapper>
    );
  }
);

SingleVideo.displayName = "SingleVideo";
export default SingleVideo;

// vue-example/src/components/SingleVideo.vue
<script setup lang="ts">
import { BlinkooSingleVideoElement } from '@blinkoo/components'
import { ref } from 'vue'
import '@blinkoo/components'

// props definition
withDefaults(
  defineProps<{
    environment?: string
    customBaseUrl?: string
    externalCustomerId?: string
    utmSource?: string
    utmCampaign?: string
    referrer?: string
    componentId?: string
    postId?: string
    autoplay?: boolean
    muted?: boolean
    showCreator?: boolean
  }>(),
  {
    // default values
    environment: undefined,
    customBaseUrl: undefined,
    assetsPath: undefined,
    externalCustomerId: undefined,
    utmSource: undefined,
    utmCampaign: undefined,
    referrer: undefined,
    componentId: undefined,
    postId: undefined,
    autoplay: undefined,
    muted: undefined,
    showCreator: undefined,
  },
)

// reference to the web component
const singleVideoRef = ref<BlinkooSingleVideoElement | null>(null)

// Expose methods for parent components to use
const togglePlay = () => singleVideoRef.value?.togglePlay()

defineExpose({
  togglePlay,
})
</script>

<template>
  <blinkoo-single-video
    ref="singleVideoRef"
    :environment="environment"
    :custom-base-url="customBaseUrl"
    :external-customer-id="externalCustomerId"
    :utm-source="utmSource"
    :utm-campaign="utmCampaign"
    :referrer="referrer"
    :component-id="componentId"
    :post-id="postId"
    :autoplay="autoplay"
    :muted="muted"
    :show-creator="showCreator"
  />
</template>
